### ISSUE TITLE
Kubernetes安装指南

### ISSUE THREAD

**Issue by tivizi** [tivizi/tivizi#8]
1. Control Plane节点进程树：
systemd:
- kube-apiserver
- kube-scheduler
- kube-controller-manager

2. Worker Plane节点进程树：
systemd:
- kubelet
- containerd

3. 覆盖网络
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```

4. Cluser IP Supports
https://www.bookstack.cn/read/kubernetes-practice-guide/deploy-addons-kube-proxy.md

5. crictl
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: crictl
  name: crictl-amd64-ds
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: crictl
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: crictl
    spec:
      containers:
      - name: crictl
        image: k8s.gcr.io/kube-proxy-${ARCH}:${VERSION}
        imagePullPolicy: IfNotPresent
        command:
        - /usr/local/bin/kube-proxy
        - --config=/var/lib/kube-proxy/config.conf
        - --hostname-override=\$(NODE_NAME)
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run/containerd/containerd.sock
          name: containerd
      volumes:
      - name: containerd
        hostPath:
          path: /run/containerd/containerd.sock
EOF
```
打完收工。
